"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import warnings

# ═══════════════════════════════════════════════════════════════════
# CHARGEMENT AUTOMATIQUE DU FICHIER .env
# Rend disponibles toutes les variables : HUGGINGFACE_TOKEN, SENTINEL_HUB_*,
# MICROSOFT_PC_API_KEY, GEE_PROJECT_ID, etc. via os.getenv() dans tout le projet.
# ═══════════════════════════════════════════════════════════════════
import environ  # NÉCESSAIRE POUR POSTGIS ET .env

# Initialisation de django-environ (seul mécanisme de chargement .env)
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
)
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# ── RÉSOLUTION CONFLIT PROJ (Rasterio vs PostGIS Windows) ──
# Pour éviter que rasterio ne lise le proj.db global de PostgreSQL (qui cause les erreurs de version),
# on force l'utilisation de sa propre base de données PROJ incluse dans le dictionnaire Python.
try:
    import rasterio
    proj_lib_path = os.path.join(os.path.dirname(rasterio.__file__), 'proj_data')
    os.environ["PROJ_LIB"] = proj_lib_path
except ImportError:
    pass
os.environ.setdefault("PROJ_IGNORE_CELESTIAL_BODY", "YES")

# ── Supprime le warning pkg_resources de coreapi (inoffensif) ──
warnings.filterwarnings("ignore", message="pkg_resources is deprecated", category=UserWarning)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', 'testserver'])
if 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Application fondation commune
    "core",
    # Module 1 Urbanisme
    "module1_urbanisme",
    # Django REST Framework
    "rest_framework",
    # Activation GÉOGRAPHIQUE (PostGIS)
    "django.contrib.gis",
    # Filtrage avancé API REST
    "django_filters",
    # CORS (M18 — nécessaire si frontend séparé)
    "corsheaders",
    # Live reload
    "django_browser_reload",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "config.urls"

# CORRECTIF D2 : Premier bloc TEMPLATES supprimé (doublon — le second bloc
# ligne 143 est complet et inclut BASE_DIR/'templates')

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ── CONFIGURATION BASE DE DONNÉES POSTGIS ──
# B5 : Utilise DATABASE_URL du .env impérativement (PostgreSQL/PostGIS)
DATABASES = {
    'default': env.db('DATABASE_URL')
}

if DATABASES['default']['ENGINE'] == 'django.contrib.gis.db.backends.postgis':
    if sys.platform == 'win32':
        # P3 CORRIGÉ : DLL Windows uniquement — Linux/Mac ignorent ce bloc
        # C4 : Chemin configurable via variable d'environnement POSTGRES_BIN_PATH
        _default_pg_bin = r"C:\Program Files\PostgreSQL\16\bin"
        POSTGRES_BIN = env('POSTGRES_BIN_PATH', default=_default_pg_bin)
        GDAL_LIBRARY_PATH = os.path.join(POSTGRES_BIN, 'libgdal-34.dll')
        GEOS_LIBRARY_PATH = os.path.join(POSTGRES_BIN, 'libgeos_c.dll')
        # On ajoute au PATH Windows pour que les DLLs dépendantes soient trouvées
        os.environ['PATH'] = POSTGRES_BIN + os.pathsep + os.environ.get('PATH', '')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# Media files for uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Templates configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Static files configuration
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Internationalization pour la Côte d'Ivoire
LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Africa/Abidjan"

# ═══════════════════════════════════════════════════════════════════
# CONFIGURATION DU LOGGING — Suppression des warnings inoffensifs
# ═══════════════════════════════════════════════════════════════════
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {},
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        # ── Silence les warnings PROJ de rasterio (conflit PostgreSQL/rasterio PROJ)
        # Impact : AUCUN — les calculs géospatiaux sont corrects
        "rasterio._env": {
            "handlers": ["console"],
            "level": "ERROR",   # On ne voit plus les CPLE_AppDefined PROJ
            "propagate": False,
        },
        # ── Silence les 403 Google API Client (GEE non authentifié — attendu)
        "googleapiclient.http": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        # ── Notre pipeline : tout voir jusqu'en INFO
        "module1_urbanisme": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "level": "WARNING",
        "handlers": ["console"],
    },
}

# ═══════════════════════════════════════════════════════════════════
# CORS — M18 : Configuration sécurisée par défaut
# En dev : CORS_ALLOW_ALL_ORIGINS = True (via DEBUG)
# En prod : définir CORS_ALLOWED_ORIGINS dans .env
# ═══════════════════════════════════════════════════════════════════
CORS_ALLOW_ALL_ORIGINS = DEBUG  # True en dev, False en prod
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
