# Generated by Django 5.2.10 on 2026-03-02 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageSatellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_acquisition", models.DateField()),
                ("satellite", models.CharField(default="Sentinel-2", max_length=50)),
                ("bands", models.JSONField(default=dict)),
                (
                    "classification_map",
                    models.FileField(upload_to="sentinel/classification/"),
                ),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Image Satellite",
                "verbose_name_plural": "Images Satellites",
            },
        ),
        migrations.CreateModel(
            name="ZoneCadastrale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_id", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("zone_type", models.CharField(max_length=50)),
                (
                    "buildable_status",
                    models.CharField(
                        choices=[
                            ("forbidden", "Zone Interdite"),
                            ("conditional", "Zone Sous Condition"),
                            ("buildable", "Zone Constructible"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "geometry_geojson",
                    models.TextField(
                        help_text="Géométrie en format GeoJSON (temporaire pour SQLite)"
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Zone Cadastrale",
                "verbose_name_plural": "Zones Cadastrales",
            },
        ),
        migrations.CreateModel(
            name="MicrosoftFootprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry_geojson",
                    models.TextField(
                        help_text="Géométrie en format GeoJSON (temporaire pour SQLite)"
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        default="Abidjan_33333010.geojsonl", max_length=100
                    ),
                ),
                (
                    "date_reference",
                    models.CharField(default="~2023-2024", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Empreinte Microsoft",
                "verbose_name_plural": "Empreintes Microsoft",
                "indexes": [
                    models.Index(
                        fields=["source_file"], name="module1_urb_source__8014c4_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DetectionConstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_detection", models.DateTimeField(auto_now_add=True)),
                (
                    "geometry_geojson",
                    models.TextField(
                        help_text="Géométrie en format GeoJSON (temporaire pour SQLite)"
                    ),
                ),
                (
                    "ndbi_t1",
                    models.FloatField(help_text="Valeur NDBI sur image T1 (référence)"),
                ),
                (
                    "ndbi_t2",
                    models.FloatField(help_text="Valeur NDBI sur image T2 (détection)"),
                ),
                (
                    "bsi_value",
                    models.FloatField(
                        blank=True,
                        help_text="Bare Soil Index pour détection terrassement",
                        null=True,
                    ),
                ),
                ("surface_m2", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField(default=0.0)),
                ("present_in_microsoft", models.BooleanField(default=False)),
                ("present_in_t1_sentinel", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("infraction_zonage", "Infraction au Zonage"),
                            (
                                "sous_condition",
                                "Zone Sous Condition - Inspection Requise",
                            ),
                            ("conforme", "Développement Conforme"),
                            (
                                "surveillance_preventive",
                                "Surveillance Préventive - Terrassement Détecté",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("rouge", "Alerte Rouge"),
                            ("orange", "Alerte Orange"),
                            ("vert", "Notification Verte"),
                            ("veille", "Mise en Veille"),
                        ],
                        max_length=10,
                    ),
                ),
                ("verification_required", models.BooleanField(default=True)),
                (
                    "statut_traitement",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("confirme", "Confirmé"),
                            ("faux_positif", "Faux positif"),
                            ("en_investigation", "En investigation"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("commentaire_terrain", models.TextField(blank=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "traitee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone_cadastrale",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="module1_urbanisme.zonecadastrale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détection de Construction",
                "verbose_name_plural": "Détections de Constructions",
                "indexes": [
                    models.Index(
                        fields=["status"], name="module1_urb_status_60c2c5_idx"
                    ),
                    models.Index(
                        fields=["alert_level"], name="module1_urb_alert_l_351d56_idx"
                    ),
                    models.Index(
                        fields=["date_detection"], name="module1_urb_date_de_1dd14f_idx"
                    ),
                    models.Index(
                        fields=["statut_traitement"],
                        name="module1_urb_statut__678857_idx",
                    ),
                ],
            },
        ),
    ]
