# Generated by Django 5.2.10 on 2026-03-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module1_urbanisme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagesatellite",
            name="classification_map",
            field=models.FileField(
                max_length=255, upload_to="sentinel/classification/"
            ),
        ),
        migrations.AlterField(
            model_name="microsoftfootprint",
            name="source_file",
            field=models.CharField(default="Abidjan_33333010.geojsonl", max_length=255),
        ),
    ]
