# Generated by Django 5.2.10 on 2026-03-21 02:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module1_urbanisme", "0002_alter_imagesatellite_classification_map_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectionconstruction",
            name="geometry_geojson",
        ),
        migrations.RemoveField(
            model_name="microsoftfootprint",
            name="geometry_geojson",
        ),
        migrations.RemoveField(
            model_name="zonecadastrale",
            name="geometry_geojson",
        ),
        migrations.AddField(
            model_name="detectionconstruction",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(
                help_text="Géométrie spatiale PostGIS", null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="microsoftfootprint",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(
                help_text="Géométrie spatiale PostGIS", null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="zonecadastrale",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(
                help_text="Géométrie spatiale PostGIS", null=True, srid=4326
            ),
        ),
    ]
