# Generated by Django 5.2.10 on 2026-03-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "module1_urbanisme",
            "0003_remove_detectionconstruction_geometry_geojson_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="microsoftfootprint",
            options={
                "verbose_name": "Empreinte Bâtiment",
                "verbose_name_plural": "Empreintes Bâtiments",
            },
        ),
        migrations.AddField(
            model_name="microsoftfootprint",
            name="confidence_score",
            field=models.FloatField(
                blank=True,
                help_text="Score de confiance Google Open Buildings (0.65-1.0). Rouge: 0.65-0.70, Jaune: 0.70-0.75, Vert: >=0.75",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="microsoftfootprint",
            name="source",
            field=models.CharField(
                choices=[
                    ("Google_V3_2023", "Google Open Buildings V3 (mai 2023)"),
                    ("Google_Temporal_V1", "Google Open Buildings Temporal V1"),
                    ("Microsoft_2020", "Microsoft Building Footprints (obsolète)"),
                ],
                default="Google_V3_2023",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="imagesatellite",
            name="classification_map",
            field=models.CharField(
                blank=True,
                help_text="Chemin absolu vers le fichier SCL (Scene Classification Layer)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="microsoftfootprint",
            name="date_reference",
            field=models.CharField(default="2023-05", max_length=50),
        ),
        migrations.AlterField(
            model_name="microsoftfootprint",
            name="source_file",
            field=models.CharField(default="google_open_buildings_v3", max_length=255),
        ),
        migrations.AddIndex(
            model_name="microsoftfootprint",
            index=models.Index(fields=["source"], name="module1_urb_source_811586_idx"),
        ),
        migrations.AddIndex(
            model_name="microsoftfootprint",
            index=models.Index(
                fields=["confidence_score"], name="module1_urb_confide_782977_idx"
            ),
        ),
    ]
