# Generated by Django 5.2.10 on 2026-04-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module1_urbanisme", "0004_alter_microsoftfootprint_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microsoftfootprint",
            name="source",
            field=models.CharField(
                choices=[
                    ("Google_V3_2023", "Google Open Buildings V3 (mai 2023)"),
                    ("Google_Temporal_V1", "Google Open Buildings Temporal V1"),
                ],
                default="Google_V3_2023",
                max_length=30,
            ),
        ),
    ]
